"""Initial tables

Revision ID: 82a0bc946da6
Revises: 
Create Date: 2026-10-03 12:03:03.310632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a0bc946da6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_sent_at'), 'email_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('member_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('non_member_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('fundraisers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('raised_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', name='fundraiserstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraisers_status'), 'fundraisers', ['status'], unique=False)
    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('ticket_discount_percent', sa.Integer(), nullable=False),
    sa.Column('merch_discount_percent', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'TREASURER', 'VOLUNTEER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('MEETING', 'DEADLINE', 'CHANGE_OF_PLAN', 'GENERAL', name='announcementcategory'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_category'), 'announcements', ['category'], unique=False)
    op.create_index(op.f('ix_announcements_published_at'), 'announcements', ['published_at'], unique=False)
    op.create_table('expense_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('fundraiser_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'REIMBURSED', name='expensestatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reimbursed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraisers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_claims_event_id'), 'expense_claims', ['event_id'], unique=False)
    op.create_index(op.f('ix_expense_claims_fundraiser_id'), 'expense_claims', ['fundraiser_id'], unique=False)
    op.create_index(op.f('ix_expense_claims_status'), 'expense_claims', ['status'], unique=False)
    op.create_index(op.f('ix_expense_claims_submitted_by_id'), 'expense_claims', ['submitted_by_id'], unique=False)
    op.create_table('fundraiser_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fundraiser_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraisers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraiser_tasks_assignee_id'), 'fundraiser_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_fundraiser_tasks_fundraiser_id'), 'fundraiser_tasks', ['fundraiser_id'], unique=False)
    op.create_index(op.f('ix_fundraiser_tasks_status'), 'fundraiser_tasks', ['status'], unique=False)
    op.create_table('mailing_list_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailing_list_subscribers_email'), 'mailing_list_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_mailing_list_subscribers_unsubscribe_token'), 'mailing_list_subscribers', ['unsubscribe_token'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'ACTIVE', 'EXPIRED', name='membershipstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('dues_paid', sa.Boolean(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('member_code', sa.String(length=64), nullable=False),
    sa.Column('renewal_reminder_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_end_date'), 'memberships', ['end_date'], unique=False)
    op.create_index(op.f('ix_memberships_member_code'), 'memberships', ['member_code'], unique=True)
    op.create_index(op.f('ix_memberships_plan_id'), 'memberships', ['plan_id'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FULFILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='productsize'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size', name='uq_product_size')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(length=100), nullable=False),
    sa.Column('buyer_email', sa.String(length=150), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_member_price', sa.Boolean(), nullable=False),
    sa.Column('ticket_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'CHECKED_IN', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_buyer_email'), 'tickets', ['buyer_email'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('source', sa.Enum('DUES', 'TICKET', 'MERCH', 'FUNDRAISER', 'DONATION', 'REIMBURSEMENT', 'OTHER', name='transactionsource'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_buyer_email'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_plan_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_member_code'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_end_date'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_mailing_list_subscribers_unsubscribe_token'), table_name='mailing_list_subscribers')
    op.drop_index(op.f('ix_mailing_list_subscribers_email'), table_name='mailing_list_subscribers')
    op.drop_table('mailing_list_subscribers')
    op.drop_index(op.f('ix_fundraiser_tasks_status'), table_name='fundraiser_tasks')
    op.drop_index(op.f('ix_fundraiser_tasks_fundraiser_id'), table_name='fundraiser_tasks')
    op.drop_index(op.f('ix_fundraiser_tasks_assignee_id'), table_name='fundraiser_tasks')
    op.drop_table('fundraiser_tasks')
    op.drop_index(op.f('ix_expense_claims_submitted_by_id'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_status'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_fundraiser_id'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_event_id'), table_name='expense_claims')
    op.drop_table('expense_claims')
    op.drop_index(op.f('ix_announcements_published_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_category'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('membership_plans')
    op.drop_index(op.f('ix_fundraisers_status'), table_name='fundraisers')
    op.drop_table('fundraisers')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_sent_at'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
